### ISSUE TITLE
Docker build?

### ISSUE THREAD

**Issue by pjmagee** [Ahli/Galaxy-Observer-UI#147]
Hey Ahli, 

Would it be possible to add a Dockerfile for docker build support using `openjdk:14`? 
So someone could modify the UI and just do a docker-build and then extract the built interface from the docker container.

**Comment by pjmagee** [comment]
Something like:

```
FROM openjdk:14

WORKDIR /app
ARG INTERFACE_FOLDER="/app/dev/heroes/AhliObs.StormInterface"

COPY . .

RUN java -jar ./dev/compile-spring-boot.jar --compile="${INTERFACE_FOLDER}"
```

but i could not get it to compile not sure what else is needed to run it from that base image.

**Comment by pjmagee** [comment]
Looks like we cant compile and run a command line version because the java uses some kind of UI framework needed I guess.

**Comment by pjmagee** [comment]
```
 => ERROR [4/4] RUN java -jar ./dev/compile-spring-boot.jar --compile="/app/dev/heroes/AhliObs.StormInterface"                                            1.4s
------
 > [4/4] RUN java -jar ./dev/compile-spring-boot.jar --compile="/app/dev/heroes/AhliObs.StormInterface":
#8 1.024 23:18:04.275 [main] INFO  interfacebuilder.InterfaceBuilderApp - Launch arguments: [--compile=/app/dev/heroes/AhliObs.StormInterface]
#8 1.024 23:18:04.275 [main] INFO  interfacebuilder.InterfaceBuilderApp - Max Heap Space: 6400mb.
#8 1.071 Graphics Device initialization failed for :  es2, sw
#8 1.071 Error initializing QuantumRenderer: no suitable pipeline found
#8 1.072 java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
#8 1.072        at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:280)
#8 1.072        at com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:244)
#8 1.072        at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:261)
#8 1.072        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:267)
#8 1.072        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
#8 1.072        at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)
#8 1.073        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:678)
#8 1.073        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
#8 1.073        at java.base/java.lang.Thread.run(Thread.java:832)
#8 1.073 Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
#8 1.073        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:94)
#8 1.073        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124)
#8 1.074        ... 1 more
```

**Comment by Ahli** [comment]
It looks like it needs to work without a UI again.

**Comment by Ahli** [comment]
Found some more info that might help: https://stackoverflow.com/questions/56994260/getting-a-javafx-11-app-to-work-on-docker

> had to install VcXsrv on my Windows host
> add this to the docker run command : -e DISPLAY=MY IP ADDRESS:0.0

**Comment by pjmagee** [comment]
Okay thats cool. It was really just to see if i could avoid any dev stuff on my machine. Ive been moving and building a lot of external things in docker. Just wanted to see if it was a quick win.

**Comment by pjmagee** [comment]
We can close the issue if its not feasible. Dont want to clutter all the more important issues
